import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from '/components/Footer'
export default function Home() {
  return (
    <div className='grid grid-cols-2 grid-row-2'>
      <Head>
        <title>Proj Match</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
      
      <Image
      src="/images/tela_inicial.jpg"
      alt="Picture of the author"
      width={1920}
      height={1920}
      className="col-span-1 row-span-1"
      />
      <div className="grid rol-start-2 rol-end-2 col-start-1 col-end-2">
      <Footer/>
      </div>
    </div>
  )
}